services:
  - type: static
    name: instagram-reels-downloader
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - path: /*
        methods:
          - GET
        dest: /index.html
